name: Build and release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wtfjoke/setup-groovy@v2
        with:
          groovy-version: '2.4.19'
      - run: groovy -cp test test/all.groovy